import React, { FC } from 'react';
import Head from "next/head";
import { NavBar } from "../NavBar";

import styles from "./MainLayout.module.css";
import { PropsWithChildren } from 'react';


export const MainLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Home - Mauricio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />

      <main className={styles.main}>{children}</main>
    </>
  );
};
